### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by joeytsq** [quincyyhuang/hexo-node-admin#15]
# npm start

> hexo-node-admin@0.1.5 start /data/git/hexo-node-admin
> node index.js

/data/git/hexo-node-admin/modules/view.js:52
async function login(req, res) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/git/hexo-node-admin/modules/router.js:3:12)

**Comment by quincyyhuang** [comment]
你的node版本是多少

**Comment by quincyyhuang** [comment]
你需要至少node v8以上版本来支持async function
